version: '3.8'

services:
 

  mysqldb:
    build:
      context: ./swagger_server/database/
      dockerfile: Dockerfile
    image: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=PITERcziter1907
    - MYSQL_DATABASE=foto_portfolio 
    - MYSQL_HOST=localhost

    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./:/usr/src/app

volumes:
  mysql:
  mysql_config: