version: '3.8'

services:
 

  mysqldb:
    
    build:
      context: ./swagger_server/database/
      dockerfile: Dockerfile
    ports:
    - 3308:3306
    environment:
    - MYSQL_ROOT_PASSWORD=PITERcziter1907
    - MYSQL_DATABASE=foto_portfolio 
    - MYSQL_HOST=localhost
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
    - python-network 

    


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./:/usr/src/app
    networks:
    - python-network 
    depends_on:
      - mysqldb
        

volumes:
  mysql:
  mysql_config:

networks:
  python-network:
    driver: bridge
